server:
  port: 3000

db:
  type: 'postgres'
  port: 5432
  database: 'instatodos'

jwt:
  expiresIn: 3600

social:
  google:
    callback: http://localhost:3000/auth/google/redirect
    redirect: http://localhost:9000/auth/google
    